### ISSUE TITLE
Generating a source map should be optional

### ISSUE THREAD

**Issue by manferlo81** [ls-age/rollup-plugin-add-shebang#2]
Hi there, I am using your plugin, in my use case it's OK because I want to generate source maps, but what if someone doesn't, an option can be added to explicitly enable/disable source maps, or you can get it from the output options. I would be glad to create a pull request. Please let me know if you are interested in this functionality.

**Comment by manferlo81** [comment]
Hi there, I dont know if I suppose to open a new issue for this, but your **package.json** should point to your type definition so if somebody use your plugin from typescript the type definitions will be found. It also helps with auto completion in some editors (VS Code for example).

**Comment by LukasHechenberger** [comment]
Thanks for pointing out these issues!

It should all be fixed in version *0.1.1*, just run `npm i rollup-plugin-add-shebang@latest` to update.
