### ISSUE TITLE
"undefined" added to output file if function doesn't return

### ISSUE THREAD

**Issue by manferlo81** [ls-age/rollup-plugin-add-shebang#77]
I noticed if you provide a function as `shebang` option and the function returns `undefined`, the plugin will add "undefined" to the top of the output file (where the shebang should be). IMO there are 2 options there, the plugin should just "skip" the addition of the "undefined" string, or it should add the default nodejs shebang (`"#!/usr/bin/env node"`). I am working on a PR for this last approach.

***example***

```javascript
// input.js

console.log("hi there!");
```

```javascript
// rollup.config.js

import addShebang from "rollup-plugin-add-shebang";

let shebang;

export default {

  input: "input.js",

  output: {
    file: "output.js",
    format: "cjs",
  },

  plugins: [
    addShebang({
      shebang() {
        return shebang;
      },
    }),
  ],

}
```

will generate...

```javascript
// output.js

undefined

console.log("hi there!");
```

**Comment by LukasHechenberger** [comment]
Well, as I see it, returning `undefined` from the shebang function is a configuration error. I think we should tell this to the user and error, instead of assuming a default value. - I guess this is just confusing and harder to debug...
